image: node:8.12.0

variables:
  NODE_ENV: development

#before_script:
#  - npm install

# stages:
  # - build
  # - test
  # - deploy

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - node_modules/
      - dist/

deploy:
  stage: deploy
  only:
    - master
  allow_failure: false
  when: manual
  script:
    - ./deploy/deploy.sh
