image: node:8.11.2

before_script:
  - 'which ssh-agent || (apt update -y && apt install openssh-client -y)'
  - npm install

stages:
  - deploy

# Despliegue solo en rama master
deploy:
  only:
    - master
  stage: deploy
  allow_failure: false
  when: manual
  script:
    - bash deploy/deploy.sh