branch-defaults:
  master:
    environment: back-b2b-production
    group_suffix: null
global:
  application_name: back-b2b
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: 64bit Amazon Linux 2018.03 v4.9.2 running Node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
